-- Morrowfield Food Co. | Retail availability and margin intelligence
-- Portable SQLite schema. The included database is generated by scripts/build_dataset.py.
-- Grain: weekly store-product sales records, weekly tracked inventory snapshots,
-- individual supplier purchase orders, and weekly store-level targets.

CREATE TABLE IF NOT EXISTS DimRegions (
    RegionID TEXT PRIMARY KEY,
    Region TEXT NOT NULL UNIQUE,
    OperatingCorridor TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DimSuppliers (
    SupplierID TEXT PRIMARY KEY,
    SupplierName TEXT NOT NULL,
    SupplierCity TEXT NOT NULL,
    SupplierRegion TEXT NOT NULL,
    ContractFillRate REAL NOT NULL,
    ContractOnTimeRate REAL NOT NULL,
    ContractLeadDays INTEGER NOT NULL,
    TemperatureBand TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DimStores (
    StoreID TEXT PRIMARY KEY,
    StoreName TEXT NOT NULL,
    City TEXT NOT NULL,
    RegionID TEXT NOT NULL REFERENCES DimRegions (RegionID),
    Region TEXT NOT NULL,
    StoreFormat TEXT NOT NULL,
    SellingAreaSqm INTEGER NOT NULL,
    OperatingSince TEXT NOT NULL,
    CommercialIndex REAL NOT NULL,
    Cluster TEXT NOT NULL,
    RegionalManager TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DimProducts (
    ProductID TEXT PRIMARY KEY,
    ProductName TEXT NOT NULL,
    Brand TEXT NOT NULL,
    Category TEXT NOT NULL,
    SupplierID TEXT NOT NULL REFERENCES DimSuppliers (SupplierID),
    ListUnitPrice REAL NOT NULL,
    StandardUnitCost REAL NOT NULL,
    BaseUnitMarginPct REAL NOT NULL,
    DemandWeight REAL NOT NULL,
    StorageType TEXT NOT NULL,
    RangeTier TEXT NOT NULL,
    InventoryTracked INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS FactSalesWeekly (
    SalesRecordID TEXT PRIMARY KEY,
    WeekStartDate TEXT NOT NULL,
    StoreID TEXT NOT NULL REFERENCES DimStores (StoreID),
    ProductID TEXT NOT NULL REFERENCES DimProducts (ProductID),
    SupplierID TEXT NOT NULL REFERENCES DimSuppliers (SupplierID),
    RecordType TEXT NOT NULL,
    Units INTEGER NOT NULL,
    ListUnitPrice REAL NOT NULL,
    DiscountRate REAL NOT NULL,
    GrossSales REAL NOT NULL,
    DiscountAmount REAL NOT NULL,
    NetSales REAL NOT NULL,
    UnitCost REAL NOT NULL,
    CostOfGoodsSold REAL NOT NULL,
    GrossProfit REAL NOT NULL,
    PromotionName TEXT NOT NULL,
    BasketCount INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS FactInventoryWeekly (
    InventoryRecordID TEXT PRIMARY KEY,
    WeekStartDate TEXT NOT NULL,
    StoreID TEXT NOT NULL REFERENCES DimStores (StoreID),
    ProductID TEXT NOT NULL REFERENCES DimProducts (ProductID),
    SupplierID TEXT NOT NULL REFERENCES DimSuppliers (SupplierID),
    OpeningUnits INTEGER NOT NULL,
    OrderedUnits INTEGER NOT NULL,
    ReceivedUnits INTEGER NOT NULL,
    ExpectedDemandUnits INTEGER NOT NULL,
    FulfilledDemandUnits INTEGER NOT NULL,
    ClosingUnits INTEGER NOT NULL,
    DaysCover REAL NOT NULL,
    AvailabilityRate REAL NOT NULL,
    StockoutHours REAL NOT NULL,
    EstimatedLostUnits INTEGER NOT NULL,
    EstimatedLostSales REAL NOT NULL,
    EstimatedLostGrossProfit REAL NOT NULL,
    LateDeliveryDays INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS FactPurchaseOrders (
    PurchaseOrderID TEXT PRIMARY KEY,
    OrderWeekStart TEXT NOT NULL,
    StoreID TEXT NOT NULL REFERENCES DimStores (StoreID),
    SupplierID TEXT NOT NULL REFERENCES DimSuppliers (SupplierID),
    OrderDate TEXT NOT NULL,
    PromisedDate TEXT NOT NULL,
    ReceivedDate TEXT NOT NULL,
    OrderedUnits INTEGER NOT NULL,
    ReceivedUnits INTEGER NOT NULL,
    FillRate REAL NOT NULL,
    DaysLate INTEGER NOT NULL,
    OnTimeFlag INTEGER NOT NULL,
    TemperatureBand TEXT NOT NULL,
    DeliveryStatus TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FactStoreTargets (
    TargetID TEXT PRIMARY KEY,
    WeekStartDate TEXT NOT NULL,
    StoreID TEXT NOT NULL REFERENCES DimStores (StoreID),
    NetSalesTarget REAL NOT NULL,
    GrossMarginTarget REAL NOT NULL,
    AvailabilityTarget REAL NOT NULL,
    SupplierFillRateTarget REAL NOT NULL,
    OnTimeDeliveryTarget REAL NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sales_store_product_week
    ON FactSalesWeekly (StoreID, ProductID, WeekStartDate);
CREATE INDEX IF NOT EXISTS idx_inventory_store_product_week
    ON FactInventoryWeekly (StoreID, ProductID, WeekStartDate);
CREATE INDEX IF NOT EXISTS idx_orders_supplier_store_week
    ON FactPurchaseOrders (SupplierID, StoreID, OrderWeekStart);

